DoYourMath/urls.py
from django.urls import path
from . import views

app_name = "DoYourMath"
urlpatterns=[
    path("",views.index, name="index"),
    path("multiplication",views.multiplication, name="multiplication"),
    path("substraction",views.substraction, name="substraction"),
    path("addition",views.addition, name="addition"),
    path("division",views.division, name="division"),
    path("answer",views.answer, name="answer")
]

masterDoYourMath/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('DoYourMath/', include("DoYourMath.urls"))
]

DoYourMath/models.py
from django.db import models

# Create your models here.

DoYourMath/views.py
from django.http import HttpResponse
from django import forms
from django.shortcuts import render
import random
import time
# Create your views here.
class NewTaskForm(forms.Form):
    """docstring ss NewTaskForm."""
    user_submitted_answer = forms.CharField(label = "Your Answer ")

def index(request):
    return render(request, "DoYourMath/index.html")

def multiplication(request):
    num1 = random.randint(100,999)
    num2 = random.randint(100,999)
    return render(request, "DoYourMath/Multiplication.html",{
    "number1" : num1,
    "number2" : num2,
    "answer" : num1 * num2,
    "form" : NewTaskForm()
    })

def substraction(request):
    num1 = random.randint(100,999)
    num2 = random.randint(100,999)
    answer= num1-num2
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            user_answer = form.cleaned_data["user_submitted_answer"]
            if(user_answer == str(answer)):
                return HttpResponse("<h1>Yes</h1>")
    return render(request, "DoYourMath/Substraction.html",{
    "number1" : num1,
    "number2" : num2,
    "answer" : answer,
    "form" : NewTaskForm()
    })




def addition(request):
    num1 = random.randint(100,999)
    num2 = random.randint(100,999)
    return render(request, "DoYourMath/Addition.html",{
    "number1" : num1,
    "number2" : num2,
    "answer" : num1 + num2,
    "form" : NewTaskForm()
    })

def division(request):
    num1 = random.randint(100,999)
    num2 = random.randint(100,999)
    answer= num1/num2
    return render(request, "DoYourMath/Division.html",{
    "number1" : num1,
    "number2" : num2,
    "answer" : answer,
    })


def answer(request,user_answer):
    return render(request, "DoYourMath/answer.html",{
    "user_answer":user_answer
    })

DoYourMath/templates/DoYourMath/Addition.html
{% extends "DoYourMath/index.html" %}
{%block body%}
<nav>
  <h1>Hey Champ! What are we solving today</h1>
  <a href="{% url 'DoYourMath:multiplication' %}">Multiplication</a>
  <a href="{% url 'DoYourMath:substraction' %}">Substraction</a>
  <a href="{% url 'DoYourMath:addition' %}" class = "active">Addition</a>
  <a href="{% url 'DoYourMath:division' %}">Division</a>
</nav>
  <div class="box">
    <h2>Addition</h2>
    <h3>{{number1}}</h3>
    <h3>{{number2}}</h3>
    <form class="" action="DoYourMath:addition" method="post">
      {% csrf_token %}
      {{ form }}
      <input type="submit"><br><br>
    </form>
    <h4>{{answer}}</h4>
    </div>
{% endblock %}

DoYourMath/templates/DoYourMath/Division.html
{% extends "DoYourMath/index.html" %}
{%block body%}
<nav>
  <h1>Hey Champ! What are we solving today</h1>
  <a href="{% url 'DoYourMath:multiplication' %}" >Multiplication</a>
  <a href="{% url 'DoYourMath:substraction' %}">Substraction</a>
  <a href="{% url 'DoYourMath:addition' %}">Addition</a>
  <a href="{% url 'DoYourMath:division' %}" class="active">Division</a>
</nav>
    <div class="box">
    <h2>Division</h2>
    <h3>{{number1}}</h3>
    <h3>{{number2}}</h3>
    <form action="{%url 'DoYourMath:division'%}" method="post">
      {% csrf_token %}
      {{ form }}
      <input type="submit"><br><br>
    </form>
    </div>
{% endblock %}

DoYourMath/templates/DoYourMath/Multiplication.html
{% extends "DoYourMath/index.html" %}
{%block body%}
<nav>
  <h1>Hey Champ! What are we solving today</h1>
  <a href="{% url 'DoYourMath:multiplication' %}" class = "active">Multiplication</a>
  <a href="{% url 'DoYourMath:substraction' %}">Substraction</a>
  <a href="{% url 'DoYourMath:addition' %}">Addition</a>
  <a href="{% url 'DoYourMath:division' %}">Division</a>
</nav>
    <div class="box">
    <h2>Multiplication</h2>
    <h3>{{number1}}</h3>
    <h3>{{number2}}</h3>
    <form class="" action="DoYourMath:multiplication" method="post">
      {% csrf_token %}
      {{ form }}
      <input type="submit"><br><br>
    </form>
    <h4>{{answer}}</h4>
    </div>
{% endblock %}

DoYourMath/templates/DoYourMath/Substraction.html
{% extends "DoYourMath/index.html" %}
{%block body%}
<nav>
  <h1>Hey Champ! What are we solving today</h1>
  <a href="{% url 'DoYourMath:multiplication' %}">Multiplication</a>
  <a href="{% url 'DoYourMath:substraction' %}" class = "active">Substraction</a>
  <a href="{% url 'DoYourMath:addition' %}">Addition</a>
  <a href="{% url 'DoYourMath:division' %}">Division</a>
</nav>
    <div class="box">
    <h2>Substraction</h2>
    <h3>{{number1}}</h3>
    <h3>{{number2}}</h3>
    <form class="" action="DoYourMath:substraction" method="POST">
      {% csrf_token %}
      {{ form }}
      <input type="submit"><br><br>
    </form>
    </div>
{% endblock %}

DoYourMath/templates/DoYourMath/answer.html
{% extends DoYourMath/index.html %}
{% block body %}
<!--{% if user_answer == answer %}
  <h4 style="color: #00ff00">Hurray! Your answer is correct</h4>
{% else %}-->
  <h4 style="color: #ff0000">Uh-oh Wrong answer,correct answer is {{user_answer}}</h4>
<!--{% endif %}-->
{% endblock %}

DoYourMath/templates/DoYourMath/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Do Your Maths</title>
    <link rel="stylesheet" href="{% static 'DoYourMath/style.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Fira+Sans&display=swap" rel="stylesheet">
  </head>
  <body>
    {% block body %}
    <nav>
    <h1>Hey Champ! What are we solving today</h1>
    <a href="{% url 'DoYourMath:multiplication' %}">Multiplication</a>
    <a href="{% url 'DoYourMath:substraction' %}">Substraction</a>
    <a href="{% url 'DoYourMath:addition' %}">Addition</a>
    <a href="{% url 'DoYourMath:division' %}">Division</a>
    </nav>

    {% endblock %}
  </body>
</html>